name: Project SAP Pipeline

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - shell: bash
        env: 
          SUPER_SECRET: ${{secrets.KUBE_CONFIG}}
        run: |
          mkdir $HOME/.kube
          echo "$SUPER_SECRET" |  base64 --decode > $HOME/.kube/config
      # Runs a single command using the runners shell
      - name: Install Helm
        run: |
           ls -la 
           curl https://baltocdn.com/helm/signing.asc | sudo apt-key add -
           sudo apt-get install apt-transport-https --yes
           echo "deb https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
           sudo apt-get update
           sudo apt-get install helm
        
      # Intstall kubetctl
      - name: Intstall kubetctl
        run: | 
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates curl
          sudo curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
          echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
          sudo apt-get update
          sudo apt-get install -y kubectl
      - name: Setup kubeconfig
        run: |
          kubectl config use-context shoot--sonar-dev--exam-gcp
          kubectl get namespaces
           kubectl get pods  -A 
  
      # Build and test App Docker Image
      - name: Build and test App Docker Image
        run: |
          cd nginx/
          # docker build --tag nginx-app .
          
      # Build and test App Docker Image
      #- name: Deploy Web server to Kubernetes with kubectl
      #  run: |
      #    kubectl apply -f nginx/nginx-namespace.yml
      #    kubectl apply -f nginx/nginx.yml
          
      # Install Ingress
      #- name: Deploy Ingress service to Kubernetes
      #  run: |
      #    helm repo add nginx-stable https://helm.nginx.com/stable 
      #    helm update repo
      #    helm install ingress nginx-stable/nginx-ingress -n ingress
      #    kubectl apply -f deployment/ingress.yaml
      
 
